let state = {
  authenticated: false,
  login: {
    emailAddress: '',
    password: '',
  },
  bankApi: {
    clientId: '',
    // endpoint: 'http://localhost:3000',
    // endpoint: 'https://bank-api-rjrico-hackathon-app.apps.openshift.iiht.tech',
    endpoint: 'https://cloudfive-bank-api-cc-uc-4-cloudfive.container-crush-02-4044f3a4e314f4bcb433696c70d13be9-0000.eu-de.containers.appdomain.cloud',
    onboardingToken: '',
    authToken: '',
  },
  step: 'tc',
  terms: false,
  onboarding: {
    firstName: '',
    middleName: '',
    lastName: '',
    suffixName: '',
    emailAddress: '',
    mobileNumber: '',
    telephoneNumber: '',
    gender: '',
    civilStatus: '',
    birthdate: '',
    birthplace: '',
    nationality: '',
    address1: '',
    address2: '',
    region: '',
    province: '',
    city: '',
    zipcode: '',
    incomeType: '',
    tin: '',
    employerBusiness: '',
    workBusinessNature: '',
    occupation: '',
    monthlyIncome: '',
  },
  errors: {
    firstName: '',
    middleName: '',
    lastName: '',
    emailAddress: '',
    mobileNumber: '',
    telephoneNumber: '',
    gender: '',
    civilStatus: '',
    birthplace: '',
    nationality: '',
    address1: '',
    address2: '',
    region: '',
    province: '',
    city: '',
    zipcode: '',
    incomeType: '',
    tin: '',
    employerBusiness: '',
    workBusinessNature: '',
    occupation: '',
    monthlyIncome: '',
  },
  regions: [],
  provinces: [],
  cities: [],
  datepicker: new Date(),

  overlay: {
    opacity: 0,
    zindex: -1,
  },

  otp: {
    i1: '',
    i2: '',
    i3: '',
    i4: '',
    i5: '',
    i6: '',
  },
  otpCode: '------',

  kycDocuments: [],

  tempPassword: '',
};
export default state;
